In [1]:
import pandas as pd


In [4]:
data = pd.read_csv("D:\\adaptive network\\data\\processed\\model_dataset.csv")
data['Label'].unique

<bound method Series.unique of 0          0
1          0
2          0
3          0
4          0
          ..
2520793    0
2520794    0
2520795    0
2520796    0
2520797    0
Name: Label, Length: 2520798, dtype: int64>

In [8]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 2520798 entries, 0 to 2520797
Data columns (total 60 columns):
 #   Column                       Dtype  
---  ------                       -----  
 0   Destination Port             int64  
 1   Flow Duration                int64  
 2   Total Fwd Packets            int64  
 3   Total Backward Packets       int64  
 4   Total Length of Fwd Packets  int64  
 5   Total Length of Bwd Packets  int64  
 6   Fwd Packet Length Max        int64  
 7   Fwd Packet Length Min        int64  
 8   Fwd Packet Length Mean       float64
 9   Fwd Packet Length Std        float64
 10  Bwd Packet Length Max        int64  
 11  Bwd Packet Length Min        int64  
 12  Bwd Packet Length Mean       float64
 13  Bwd Packet Length Std        float64
 14  Flow Bytes/s                 float64
 15  Flow Packets/s               float64
 16  Flow IAT Mean                float64
 17  Flow IAT Std                 float64
 18  Flow IAT Max                 int64  
 19  Flow IAT Mi

In [9]:
x = data.drop('Label', axis=1)
y = data['Label']

In [10]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42, stratify=y)

In [11]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

x_train_scaled = scaler.fit_transform(X_train)
x_test_scaled = scaler.transform(X_test)

In [12]:
from sklearn.ensemble import IsolationForest

model = IsolationForest(
    n_estimators=100,
    contamination= "auto",
    random_state=42
)

In [13]:
model.fit(x_train_scaled)

,"random_state random_state: int, RandomState instance or None, default=NoneControls the pseudo-randomness of the selection of the featureand split values for each branching step and each tree in the forest.Pass an int for reproducible results across multiple function calls.See :term:`Glossary <random_state>`.",42
,"n_estimators n_estimators: int, default=100The number of base estimators in the ensemble.",100
,"max_samples max_samples: ""auto"", int or float, default=""auto""The number of samples to draw from X to train each base estimator.- If int, then draw `max_samples` samples.- If float, then draw `max_samples * X.shape[0]` samples.- If ""auto"", then `max_samples=min(256, n_samples)`.If max_samples is larger than the number of samples provided,all samples will be used for all trees (no sampling).",'auto'
,"contamination contamination: 'auto' or float, default='auto'The amount of contamination of the data set, i.e. the proportionof outliers in the data set. Used when fitting to define the thresholdon the scores of the samples.- If 'auto', the threshold is determined as in the original paper.- If float, the contamination should be in the range (0, 0.5]... versionchanged:: 0.22 The default value of ``contamination`` changed from 0.1 to ``'auto'``.",'auto'
,"max_features max_features: int or float, default=1.0The number of features to draw from X to train each base estimator.- If int, then draw `max_features` features.- If float, then draw `max(1, int(max_features * n_features_in_))` features.Note: using a float number less than 1.0 or integer less than number offeatures will enable feature subsampling and leads to a longer runtime.",1.0
,"bootstrap bootstrap: bool, default=FalseIf True, individual trees are fit on random subsets of the trainingdata sampled with replacement. If False, sampling without replacementis performed.",False
,"n_jobs n_jobs: int, default=NoneThe number of jobs to run in parallel for :meth:`fit`. ``None`` means 1unless in a :obj:`joblib.parallel_backend` context. ``-1`` means usingall processors. See :term:`Glossary <n_jobs>` for more details.",None
,"verbose verbose: int, default=0Controls the verbosity of the tree building process.",0
,"warm_start warm_start: bool, default=FalseWhen set to ``True``, reuse the solution of the previous call to fitand add more estimators to the ensemble, otherwise, just fit a wholenew forest. See :term:`the Glossary <warm_start>`... versionadded:: 0.21",False
Name,Type,Value
estimator_ estimator_: :class:`~sklearn.tree.ExtraTreeRegressor` instanceThe child estimator template used to create the collection offitted sub-estimators... versionadded:: 1.2 `base_estimator_` was renamed to `estimator_`.,ExtraTreeRegressor,ExtraTreeRegr...ndom_state=42)


In [14]:
y_pred = model.predict(x_test_scaled)

In [15]:
print(y_pred)

[1 1 1 ... 1 1 1]


In [ ]:
import numpy as np

y_pred = np.where(y_pr
ed == -1, 1, 0)

In [17]:
np.unique(y_pred, return_counts=True)

(array([0, 1]), array([457963,  46197]))

In [19]:
np.unique(model.predict(x_test_scaled), return_counts=True)

(array([-1,  1]), array([ 46197, 457963]))

In [21]:
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report
)

print("Accuracy :", accuracy_score(y_test, y_pred))
print("Precision:", precision_score(y_test, y_pred))
print("Recall   :", recall_score(y_test, y_pred))
print("F1 Score :", f1_score(y_test, y_pred))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

Accuracy : 0.8124543795620438
Precision: 0.3982076758231054
Recall   : 0.21604735284445906
F1 Score : 0.2801172484677757

Confusion Matrix:
[[391211  27801]
 [ 66752  18396]]

Classification Report:
              precision    recall  f1-score   support

           0       0.85      0.93      0.89    419012
           1       0.40      0.22      0.28     85148

    accuracy                           0.81    504160
   macro avg       0.63      0.57      0.59    504160
weighted avg       0.78      0.81      0.79    504160



In [23]:
import joblib

joblib.dump(model, "isolation_forest.pkl")
joblib.dump(scaler, "scaler.pkl")

['scaler.pkl']

In [2]:
import pandas as pd

dataforae = pd.read_csv("D:\\adaptive network\\data\\processed\\model_dataset.csv")
print(dataforae.columns)

Index(['Destination Port', 'Flow Duration', 'Total Fwd Packets',
       'Total Backward Packets', 'Total Length of Fwd Packets',
       'Total Length of Bwd Packets', 'Fwd Packet Length Max',
       'Fwd Packet Length Min', 'Fwd Packet Length Mean',
       'Fwd Packet Length Std', 'Bwd Packet Length Max',
       'Bwd Packet Length Min', 'Bwd Packet Length Mean',
       'Bwd Packet Length Std', 'Flow Bytes/s', 'Flow Packets/s',
       'Flow IAT Mean', 'Flow IAT Std', 'Flow IAT Max', 'Flow IAT Min',
       'Fwd IAT Total', 'Fwd IAT Mean', 'Fwd IAT Std', 'Fwd IAT Max',
       'Fwd IAT Min', 'Bwd IAT Total', 'Bwd IAT Mean', 'Bwd IAT Std',
       'Bwd IAT Max', 'Bwd IAT Min', 'Fwd Header Length', 'Bwd Header Length',
       'Fwd Packets/s', 'Bwd Packets/s', 'Min Packet Length',
       'Max Packet Length', 'Packet Length Mean', 'Packet Length Std',
       'Packet Length Variance', 'Down/Up Ratio', 'Average Packet Size',
       'Avg Fwd Segment Size', 'Avg Bwd Segment Size', 'Subflow Fwd Pack

In [4]:
import pandas as pd
import numpy as np
import joblib

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import IsolationForest

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report
)


# ============================================================
# 1. LOAD DATASET
# ============================================================

CSV_PATH = "../data/processed/model_dataset.csv"

print("Loading dataset...")

df = pd.read_csv(CSV_PATH)

print("Dataset shape:", df.shape)


# ============================================================
# 2. SEPARATE FEATURES AND LABEL
# ============================================================

LABEL_COLUMN = "Label"

X = df.drop(columns=[LABEL_COLUMN])
y = df[LABEL_COLUMN].astype(int)


# ============================================================
# 3. LABEL DISTRIBUTION
# ============================================================

print("\nLabel distribution:")
print(y.value_counts())


# ============================================================
# 4. KEEP NUMERIC FEATURES ONLY
# ============================================================

X = X.select_dtypes(include=[np.number])

print("\nNumber of features:", X.shape[1])


# ============================================================
# 5. HANDLE INVALID VALUES
# ============================================================

X = X.replace([np.inf, -np.inf], np.nan)

X = X.fillna(0)


# ============================================================
# 6. TRAIN / TEST SPLIT
# ============================================================

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)


# ============================================================
# 7. STANDARD SCALER
# ============================================================

scaler = StandardScaler()

x_train_scaled = scaler.fit_transform(X_train)
x_test_scaled = scaler.transform(X_test)

print("\nScaling completed.")


# ============================================================
# 8. TRAIN ISOLATION FOREST
# ============================================================

print("\nTraining Isolation Forest...")

model = IsolationForest(
    n_estimators=100,
    contamination="auto",
    random_state=42
)

model.fit(x_train_scaled)

print("Isolation Forest training completed.")


# ============================================================
# 9. NORMAL IF PREDICTIONS
# ============================================================

y_pred_raw = model.predict(x_test_scaled)

# Isolation Forest:
#  1  = normal
# -1  = anomaly

y_pred = np.where(
    y_pred_raw == -1,
    1,
    0
)


# ============================================================
# 10. MODEL EVALUATION
# ============================================================

print("\n==============================")
print("MODEL EVALUATION")
print("==============================")

print(
    "Accuracy :",
    accuracy_score(y_test, y_pred)
)

print(
    "Precision:",
    precision_score(
        y_test,
        y_pred,
        zero_division=0
    )
)

print(
    "Recall   :",
    recall_score(
        y_test,
        y_pred,
        zero_division=0
    )
)

print(
    "F1 Score :",
    f1_score(
        y_test,
        y_pred,
        zero_division=0
    )
)

print("\nConfusion Matrix:")

print(
    confusion_matrix(
        y_test,
        y_pred
    )
)

print("\nClassification Report:")

print(
    classification_report(
        y_test,
        y_pred,
        zero_division=0
    )
)


# ============================================================
# 11. GET RAW ISOLATION FOREST SCORES
# ============================================================

print("\n==============================")
print("ISOLATION FOREST SCORE RANGE")
print("==============================")


# score_samples():
# Higher values = more normal
#
# We use negative score so that:
# Higher value = more anomalous

train_if_scores = -model.score_samples(
    x_train_scaled
)

test_if_scores = -model.score_samples(
    x_test_scaled
)


# ============================================================
# 12. PRINT SCORE RANGE
# ============================================================

print(
    "\nIF score minimum:",
    train_if_scores.min()
)

print(
    "IF score maximum:",
    train_if_scores.max()
)

print(
    "\nTest IF score minimum:",
    test_if_scores.min()
)

print(
    "Test IF score maximum:",
    test_if_scores.max()
)


# ============================================================
# 13. PRINT PERCENTILES
# ============================================================

print("\n==============================")
print("IF SCORE PERCENTILES")
print("==============================")

for percentile in [90, 95, 97, 99]:

    value = np.percentile(
        train_if_scores,
        percentile
    )

    print(
        f"{percentile}%:",
        value
    )


# ============================================================
# 14. SAVE MODEL
# ============================================================

MODEL_PATH = "../models/saved_models/isolation_forest.pkl"

joblib.dump(
    model,
    MODEL_PATH
)

print(
    "\nIsolation Forest saved to:",
    MODEL_PATH
)


# ============================================================
# 15. SAVE SCALER
# ============================================================

SCALER_PATH = "../models/saved_models/scaler.pkl"

joblib.dump(
    scaler,
    SCALER_PATH
)

print(
    "Scaler saved to:",
    SCALER_PATH
)


print("\n==============================")
print("DONE")
print("==============================")

Loading dataset...
Dataset shape: (2520798, 60)

Label distribution:
Label
0    2095057
1     425741
Name: count, dtype: int64

Number of features: 59

Scaling completed.

Training Isolation Forest...
Isolation Forest training completed.

MODEL EVALUATION
Accuracy : 0.8124543795620438
Precision: 0.3982076758231054
Recall   : 0.21604735284445906
F1 Score : 0.2801172484677757

Confusion Matrix:
[[391211  27801]
 [ 66752  18396]]

Classification Report:
              precision    recall  f1-score   support

           0       0.85      0.93      0.89    419012
           1       0.40      0.22      0.28     85148

    accuracy                           0.81    504160
   macro avg       0.63      0.57      0.59    504160
weighted avg       0.78      0.81      0.79    504160


ISOLATION FOREST SCORE RANGE

IF score minimum: 0.3152306288090104
IF score maximum: 0.764886014545834

Test IF score minimum: 0.31536551888577985
Test IF score maximum: 0.7471522449266593

IF SCORE PERCENTILES
90%: 0

In [3]:
import pandas as pd

df = pd.read_csv("../data/processed/model_dataset.csv")

print(df["Label"].value_counts(dropna=False))
print("\nUnique labels:")
print(df["Label"].unique())

Label
0    2095057
1     425741
Name: count, dtype: int64

Unique labels:
[0 1]
